package life.hjh.community.model;

public class JobInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.id
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.company_name
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.company_addr
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private String companyAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_name
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_addr
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private String jobAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.salary_min
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private Integer salaryMin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.salary_max
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private Integer salaryMax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.url
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.time
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private Long time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.details
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.id
     *
     * @return the value of job_info.id
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.id
     *
     * @param id the value for job_info.id
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.company_name
     *
     * @return the value of job_info.company_name
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.company_name
     *
     * @param companyName the value for job_info.company_name
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.company_addr
     *
     * @return the value of job_info.company_addr
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public String getCompanyAddr() {
        return companyAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.company_addr
     *
     * @param companyAddr the value for job_info.company_addr
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setCompanyAddr(String companyAddr) {
        this.companyAddr = companyAddr == null ? null : companyAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_name
     *
     * @return the value of job_info.job_name
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_name
     *
     * @param jobName the value for job_info.job_name
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_addr
     *
     * @return the value of job_info.job_addr
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public String getJobAddr() {
        return jobAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_addr
     *
     * @param jobAddr the value for job_info.job_addr
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setJobAddr(String jobAddr) {
        this.jobAddr = jobAddr == null ? null : jobAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.salary_min
     *
     * @return the value of job_info.salary_min
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public Integer getSalaryMin() {
        return salaryMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.salary_min
     *
     * @param salaryMin the value for job_info.salary_min
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setSalaryMin(Integer salaryMin) {
        this.salaryMin = salaryMin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.salary_max
     *
     * @return the value of job_info.salary_max
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public Integer getSalaryMax() {
        return salaryMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.salary_max
     *
     * @param salaryMax the value for job_info.salary_max
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setSalaryMax(Integer salaryMax) {
        this.salaryMax = salaryMax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.url
     *
     * @return the value of job_info.url
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.url
     *
     * @param url the value for job_info.url
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.time
     *
     * @return the value of job_info.time
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public Long getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.time
     *
     * @param time the value for job_info.time
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setTime(Long time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.details
     *
     * @return the value of job_info.details
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.details
     *
     * @param details the value for job_info.details
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}