package life.hjh.community.model;

public class JobInfoWithBLOBs extends JobInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.company_info
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private String companyInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column job_info.job_info
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    private String jobInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.company_info
     *
     * @return the value of job_info.company_info
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public String getCompanyInfo() {
        return companyInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.company_info
     *
     * @param companyInfo the value for job_info.company_info
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setCompanyInfo(String companyInfo) {
        this.companyInfo = companyInfo == null ? null : companyInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column job_info.job_info
     *
     * @return the value of job_info.job_info
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public String getJobInfo() {
        return jobInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column job_info.job_info
     *
     * @param jobInfo the value for job_info.job_info
     *
     * @mbg.generated Sun May 17 01:31:17 CST 2020
     */
    public void setJobInfo(String jobInfo) {
        this.jobInfo = jobInfo == null ? null : jobInfo.trim();
    }
}